### ISSUE TITLE
Molfile IO and validation

### ISSUE THREAD

**Issue by JanCBrammer** [TUCAN-nest/TUCAN#66]
This is a more targeted issue to continue the discussion we started in #60.

**Comment by flange-ipb** [comment]
I would add the following things:
- [ ] Molfile version validation ("V3000" in line 4)
- [ ] line wrapping after "-" (only lines starting with "M&nbsp;&nbsp;V30")
- [ ] look for "COUNTS" in line 6
- [ ] look for "BEGIN ATOM" and "END ATOM" within `_parse_atom_block_molfile3000`
- [ ] look for "BEGIN BOND" and "END BOND" within `_parse_bond_block_molfile3000`
- [ ] for each bond tuple (u, v): check if u and v are keys in the `atom_props` dict
- [ ] if something is wrong: raise an exception (I'd prefer to define a custom exception class, like `MolfileParserException`)

Problematic (from the point of view of telling the user what is wrong):
- KeyError in `ELEMENT_PROPS[element_symbol]` due to an unknown element symbol
- IndexError
- ValueError when type conversions fail (`int()` and `float()`)
